spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dietnote?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: adcap
    password: adcap0902!
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  path-to-match:
    - /api/**